### ISSUE TITLE
Is it possible to replace Tyrus with other websocket clients?

### ISSUE THREAD

**Issue by jarvislin** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#15]
Hi,
I found that Tyrus causes handshake failure on some Android devices,
so I replace Tyrus with other websocket clients.
(I tried OkHttp, nv-websocket-client and copy the URI to websocket.org)

But  I just got `403 Forbidden` when I tried to connect.

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-android/blob/master/src/main/java/com/amazonaws/kinesisvideo/signaling/tyrus/WebSocketClient.java#L45

It seems Tyrus uses RFC 6455 in the above file and I had tried other client which supports RFC 6455, but still got the same error.

I would like to know: Is there anything I have to notice if I want to connect to the WebSocket endpoint.

**Comment by pozhega** [comment]
@jarvislin hi, have you ever managed to solve this problem?

**Comment by JeetSA** [comment]
Hello @jarvislin ,

Did you resolve this issue? Can you please help me for the same?

Thanks in advance.

**Comment by nickhuang9527** [comment]
@jarvislin @pozhega @JeetSA 

I think the problem is that WSS URI is encoded twice and the 'tyrus' is work perfectly on that, but not 'okhttp' and 'Java-WebSocket'

1. All query params are encoded in buildQueryParamsMap function  (e.g.  '/' -> '%2F')
2. URI init will encode it again (e.g. '%' -> '%25' '%2F' -> '%252F')

Here is my solution below
Replace
```
uriResult = URI(
       wssUri.scheme,
       wssUri.rawAuthority,
       getCanonicalUri(uri),
       signedCanonicalQueryString,
       null
)
```
with
```
val scheme = wssUri.scheme
val rawAuthority = wssUri.rawAuthority
val path = getCanonicalUri(uri)
uriResult = URI("$scheme://$rawAuthority$path?$signedCanonicalQueryString")
```

More information about java.net.URI encode
https://stackoverflow.com/questions/4858108/url-to-uri-encoding-changes-a-3d-to-253d
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-android/issues/74
