### ISSUE TITLE
Low Output Volume

### ISSUE THREAD

**Issue by prechtelm** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#28]
Hi,
the volume is extremly low. How can we increase audio output volume? We tried this without any success:

`remoteAudioTrack.setVolume(1.3);`

**Comment by MushMal** [comment]
The sample application does not configure the mic settings. Perhaps, you can change it in the system settings or modify the sample to change the sensitivity - if that's the root cause. Check if the receiving and reproducing device has the right volume too. This is not related to KVS signaling which is the asset in question here
