### ISSUE TITLE
android api or sample code  for aws security token service ?

### ISSUE THREAD

**Issue by ynaver-github** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#91]
1) 
android sample use congito but I like to use way such as AWS Security Token Service 
awslabs/amazon-kinesis-video-streams-webrtc-sdk-android

https://aws.amazon.com/ko/articles/authenticating-users-of-aws-mobile-applications-with-a-token-vending-machine/
AWS Security Token Service

is there any sample code for android ?

2) 
with  cognitoIdentity ( pollId, identityId, token ), this there any android api to get Credentials ( AccessKeyId SecretKey: SessionToken ) ?

**Comment by hassanctech** [comment]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-android/blob/d39fb09be837c3b8a75a5d6ee604409f4bc69ce6/src/main/java/com/amazonaws/kinesisvideo/demoapp/KinesisVideoWebRtcDemoApp.java#L23

Instead of returning `AWSMobileClient.getInstance` you need to build your own credentials using the `AWSCredentialsProvider` interface with the accesskey/secretkey/token and try that out.  Of course when the session token expires the connection will also stop working since credentials with a session token are always temporary.

**Comment by sirknightj** [comment]
https://github.com/codingspirit/amazon-kinesis-video-streams-webrtc-sdk-android/commit/358ed510d04ff1ba449fa1e505c8b65a3252b192
